version: "3.9"
services:
    campfire-bot:
        container_name: 'campfirebot'
        hostname: 'campfirebot'
        image: 'flamespinner/campfirebot04f20ef:latest'
        environment:
            - ttvClientId
            - ttvAppAccessToken
            - ttvClientSecret
            - ttvClientRefreshToken
            - ttvAppID
            - ttvChannel
            - discordToken
            - discordTTVLogChannel
            - discordTTVLiveChannel
            - discordGuildId
            - discordClientId
            - discordActivity
            - obsPassword
            - secret
            - userID
            - dbURI
        restart: unless-stopped